version: '3'
services:
  cassandra:
    container_name: cass
    image: cassandra:3.11.3
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    volumes:
      - ./cassandra/data:/var/lib/cassandra
    networks:
      appNet:
        ipv4_address: 172.20.0.3
  
  express:
    container_name: exp
    image: node:10.11.0-alpine
    working_dir: /usr/src/app
    ports:
      - '8888:8888'
    volumes:
      - ./express/api:/usr/src/app
    entrypoint:
      - node 
      - apiServer.js
    networks:
      appNet:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

volumes:
  db-data:
  
networks:
  appNet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.20.0.0/16